sudo: required

language: node_js

services:
  - docker

env:
  global:
  - DOCKER_IMAGE_NAME=hefesoft/horizon
  - COMMIT=${TRAVIS_COMMIT::8}
  - secure: JTgO3WokC8ShbfPe7w5jy7Ja0LGjPZDE5kXcIrG6HBhgiMaZQIETlN49CF2PT9fSwho61eBBwO+gaoF31vUmKbElmunmQv0KQFmNL1kRWLHDnVsseDVXmVOA35/vdMc/Itqh16vkNBOwdgY54yP8IL1CE8TYKo2kDAM7wLLEg3widT8soJofKShNgmfLURzMhoLgqxi9zS+0tZ33CgBD5u5EbhfWgT9uTQ7vQCKJ74JgJ835oQ2veO8Tp2V4eZKYZSPLwSoj/C2UgqH92a3lA0kbyEdkKY6rM9QCa7LGkYZkclAKZVDURRGd/d5YdCA65IH1Ceq//GBsn5cuUfFvQTatzt/k9hRjCGCoUGBk5DpqAG43rM+tB1yGnzYEhSd2p6uFv3v1VrepGJ/OgVN5Vc2kNAN/o1hwi0z964rLY5ZE536svWbmpT6s7ccO+jgzEdzyV8iuQhmQZbFIE8+wDhlcgta5LPWmik5kg1cf3OJibkUgerctpsX95c+PUoKUQHY0Rdi6y3GNlKwMXa9fSm4tTJO/RBFdH27HCv/yloc/4g5JojAmZdRPk/ejwqix/gTndxMvXsx+jbtIAtYZYa9ptGcnzG0WhsCbB/TisyCCIIeal3N/pxk8+lj4WdIPTwzYiCPQY7eG9rVfe2CPr5UEaB5S+QN1m320puDBAD4=
  - secure: I6FPIniPbQTSdk79i/w0CCGyCw7+n/e9ZnMSHuoiQASmTVGroMxEUgpG6WlCNDj5N/9IbE0UjV+DyyUeZma1SX4ZTqcpKDR67yHAbK0qX2f1u0QHbeHwpUhC47Av+uUwHXALUuk5mMpjjOBsi0ijjO05x3jp92R/h74yU+B8v38m4o+m6J6sHsnLMz65c/DkdWpIa/2iSC5hV87UiU2Hg+RD/geSuOAQ/IQL5S6tfGn+sZvQg0lmtrBDG6EaI24zOUrxizweS05o6LbeOQHe2XJCFRHE16N+J1tyqXf5HRGdlVv3WsIp3VIzZzkoAiblaQaqfFyt1FLPJGLcL4W6ofS/5nI9xTgi1Hyi1wjGh09oUN07XDcCNRocc2ufuM6PCQQJSZSZiKv3S33Rkbgoe2QwUdZlVOC9e7f+jEigdcRmRJewvMj2OI2D+rxoE0lU59po+6hVmnFECnIpZM5nQupD8MZd7Opkv7dNopSIcKr5clKlBnTsDjVkNRguD7tccIJ831+ZjJJuHBgwhCKkpaNrK43G0V7ZaR+twTWJ1epMaZ6KgB0IcsD27ZAuSaxwTUizizqFgciMpntugJjgOTHBcTHXC0N8BcHJeSOioONWZ5zAoXFUJZVoj5j0D+GDxnPmPrQ7zQZvra35vtKcWsmV7EsA00Z9ZSqlRQmaudk=
  - secure: xBSsFb5f3kQuLJk1zbsjOXOtKca1YkAaHZ3yBFw+RZy1WI4FwPHttLnq5OsLu+OREiNomT/9XsuPhy2a92M6i+z+bY7aKQnyM5dLQIDWQn0YKKBETNZkqRQaegTFWXgIujseIsGvFemWmZT1ZXVW5W30lV91ZJvs/wTCU5q2rzE4nfHJIWYsNH7QcLGfdH4fhS1S7s6fAPASySJzlmfbz8y2cuJrykmwjUFEK+iE2yfJzz+V7uvOkk2AQD/CP3tngF4D5LqeVsD5FyHQpnaxQOW/Ls1Wm9L39HwgtendmpXAJ4zcl2Y4rI21mug8ijoqS/hBzPW/4IpNwGWRri+BhTj5CKLx2Mtpq/+qkeVaBXLs8zRUIVyxHPmzYN0WsZRZlC4ae2/PJEmYCaRd3yNUO/SDGi09DSi+z5pKzmk2OGrFAbfI5T1awxolKcgoisTviaEzqdKgMfp87mXGHl45AH5tkMFjWGZUPofU2dB7svoWpL12tIBdzk9KNlSYC/+fBYmUOXHhqOrXmPFa1HZBFA8tGRTMxJg+q0Yp8zZCGwSk5xavepeJuMzzLRCxnYgLFpH0CoJLZFb6g0aopEjKJdBCHTKU8lqdvP6sl+sCYUBtT4tu7TMexTPrFxRXxnnp80dJROS5Cnh9+dwfmfRJDyGpyak7AClrs7f3YHTAX80=
after_success:
 - docker login -e="$DOCKER_EMAIL" -u="$DOCKER_USER" -p="$DOCKER_PASS"
 - docker build -f Dockerfile -t $DOCKER_IMAGE_NAME .
 - if [ ! -z "$TRAVIS_TAG" ]; then
      docker tag $DOCKER_IMAGE_NAME:latest $DOCKER_IMAGE_NAME:$TRAVIS_TAG;
    fi
 - if [ "$TRAVIS_BRANCH" == "master" ]; then
      docker push $DOCKER_IMAGE_NAME;
    fi
