version: "2.0"
services:
 db:
   image: rethinkdb
   ports:
     - "28015:28015"
     - "8080:8080"
 web:
   build: .
   environment:
    RDB_HOST: db
    RDB_PORT: 28015
    PROJECT_NAME: Hefesoft
    TOKEN_SECRET: Hefesoft123
    ALLOW_ANONYMOUS: true
    ALLOW_UNAUTHENTICATED : true
    CREATE_COLLECTION : true
    CREATE_INDEX : true
    PERMISSION : true
   depends_on:
     - db
   ports:
     - "8081:8081"