version: "2.0"
services:
 db:
   image: rethinkdb
   ports:
     - "28015:28015"
     - "8080:8080"
 web:
   build: .
   environment:
    RDB_HOST: db
    RDB_PORT: 28015
    PROJECT_NAME: Hefesoft
    TOKEN_SECRET: Hefesoft123
    ALLOW_ANONYMOUS: 1
    ALLOW_UNAUTHENTICATED : 1
    CREATE_COLLECTION : 1
    CREATE_INDEX : 1
    PERMISSION : 0
   depends_on:
     - db
   ports:
     - "8081:8081"